-- MySQL Script generated by MySQL Workbench
-- Thu Dec 13 17:10:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema AlekseevStanislavDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AlekseevStanislavDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlekseevStanislavDB` DEFAULT CHARACTER SET utf8 ;
USE `AlekseevStanislavDB` ;

-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Workers` (
  `Passport` INT NOT NULL,
  `First Name` VARCHAR(45) NULL DEFAULT NULL,
  `Last Name` VARCHAR(45) NULL DEFAULT NULL,
  `Fathers Name` VARCHAR(45) NULL DEFAULT NULL,
  `Science degree` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Passport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Patients` (
  `idPatients` INT NOT NULL,
  `First Name` VARCHAR(45) NULL DEFAULT NULL,
  `Last Name` VARCHAR(45) NULL DEFAULT NULL,
  `Fathers Name` VARCHAR(45) NULL DEFAULT NULL,
  `Passport Series` INT NULL DEFAULT NULL,
  `Passport Number` INT NULL DEFAULT NULL,
  `Adress` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPatients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`Specialisations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Specialisations` (
  `idSpecializations` INT NOT NULL,
  `SpName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSpecializations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`ConsultingRooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`ConsultingRooms` (
  `idCab` INT NOT NULL,
  `NUMcab` INT NULL DEFAULT NULL,
  `StartWork` TIME NULL DEFAULT NULL,
  `EndWork` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idCab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`Specialists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Specialists` (
  `PassportSP` INT NOT NULL,
  `idSpecializationsSP` INT NOT NULL,
  `idCabSP` INT NOT NULL,
  `idSpecialist` INT NOT NULL,
  INDEX `fk_Specialists_Workers_idx` (`PassportSP` ASC) VISIBLE,
  INDEX `fk_Specialists_Specialisations1_idx` (`idSpecializationsSP` ASC) VISIBLE,
  INDEX `fk_Specialists_ConsultingRooms1_idx` (`idCabSP` ASC) VISIBLE,
  PRIMARY KEY (`idSpecialist`),
  CONSTRAINT `fk_Specialists_Workers`
    FOREIGN KEY (`PassportSP`)
    REFERENCES `AlekseevStanislavDB`.`Workers` (`Passport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialists_Specialisations1`
    FOREIGN KEY (`idSpecializationsSP`)
    REFERENCES `AlekseevStanislavDB`.`Specialisations` (`idSpecializations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialists_ConsultingRooms1`
    FOREIGN KEY (`idCabSP`)
    REFERENCES `AlekseevStanislavDB`.`ConsultingRooms` (`idCab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`PatientsCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`PatientsCard` (
  `idPatientsPC` INT NOT NULL,
  INDEX `fk_PatientsCard_Patients1_idx` (`idPatientsPC` ASC) VISIBLE,
  CONSTRAINT `fk_PatientsCard_Patients1`
    FOREIGN KEY (`idPatientsPC`)
    REFERENCES `AlekseevStanislavDB`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`SEANSI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`SEANSI` (
  `Specialists_idSpecialist` INT NOT NULL,
  INDEX `fk_SEANSI_Specialists1_idx` (`Specialists_idSpecialist` ASC) VISIBLE,
  CONSTRAINT `fk_SEANSI_Specialists1`
    FOREIGN KEY (`Specialists_idSpecialist`)
    REFERENCES `AlekseevStanislavDB`.`Specialists` (`idSpecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`diagnosis` (
  `iddiagnosis` INT NOT NULL,
  `nameDia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iddiagnosis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`sessions` (
  `idsessions` INT NOT NULL,
  `Specialists_idSpecialists` INT NOT NULL,
  `Patients_idPatients` INT NOT NULL,
  `timeStart` TIME NULL DEFAULT NULL,
  `timeFinish` TIME NULL DEFAULT NULL,
  `diagnosis_iddiagnosis` INT NOT NULL,
  `lechenie` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsessions`),
  INDEX `fk_sessions_Specialists1_idx` (`Specialists_idSpecialists` ASC) VISIBLE,
  INDEX `fk_sessions_Patients1_idx` (`Patients_idPatients` ASC) VISIBLE,
  INDEX `fk_sessions_diagnosis1_idx` (`diagnosis_iddiagnosis` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_Patients1`
    FOREIGN KEY (`Patients_idPatients`)
    REFERENCES `AlekseevStanislavDB`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_diagnosis1`
    FOREIGN KEY (`diagnosis_iddiagnosis`)
    REFERENCES `AlekseevStanislavDB`.`diagnosis` (`iddiagnosis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlekseevStanislavDB`.`PatientsDiagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`PatientsDiagnosis` (
  `Patients_idPatients` INT NOT NULL,
  `diagnosis_iddiagnosis` INT NOT NULL,
  INDEX `fk_PatientsDiagnosis_Patients1_idx` (`Patients_idPatients` ASC) VISIBLE,
  INDEX `fk_PatientsDiagnosis_diagnosis1_idx` (`diagnosis_iddiagnosis` ASC) VISIBLE,
  CONSTRAINT `fk_PatientsDiagnosis_Patients1`
    FOREIGN KEY (`Patients_idPatients`)
    REFERENCES `AlekseevStanislavDB`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PatientsDiagnosis_diagnosis1`
    FOREIGN KEY (`diagnosis_iddiagnosis`)
    REFERENCES `AlekseevStanislavDB`.`diagnosis` (`iddiagnosis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
